### ISSUE TITLE
Add current station player controls

### ISSUE THREAD

**Issue by desaetiis** [desaetiis/raddio#11]
As a sticky footer

**Comment by desaetiis** [comment]
Only implement HTML audio here. The station sections should only have the stream url and the station info + a play button. When the button is pressed, we grab the stream url and pass it to this player.

**Comment by desaetiis** [comment]
Stop the current stream and start the new one.

**Comment by rcandea** [comment]
I vote for delaying this. Now we have n players for n streams. You are trying to build one player that might change stream. You are implementing an audio player. There are so many to choose from, better pick one instead of implementing one.

**Comment by desaetiis** [comment]
still looking at jplayer. Seems to be doing it all. Fallback to flash; current track...
